version: '3.8'

services:
  server:
    build: .
    restart: always
    ports:
      - "6363:6363"
    volumes:
      - ./db:/usr/app/db
      - ./file-checkpoints:/usr/app/file-checkpoints
      - ./.env:/usr/app/.env
    command: ["/usr/app/restart_server.sh"]
    healthcheck:
      test: ["CMD", "/usr/app/collect_process_data.sh"]
      interval: 60s
      timeout: 59s
      retries: 0
      start_period: 60s
