name: 🦘 Test & Deploy AO Sequencer Unit
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "servers/su/**"
  push:
    branches:
      - main
    paths:
      - "servers/su/**"

defaults:
  run:
    shell: bash

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run Tests
        working-directory: servers/su
        run: cargo test

  
  publish:
    runs-on: ubuntu-latest
    # Only publish on main branch
    if: github.ref == 'refs/heads/main'
    needs: [test]
    permissions:
      id-token: write
      contents: read
      checks: write
      packages: write
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.bump.outputs.TAG }}

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push binary image to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          push: true
          context: servers/su
          tags: |
            ghcr.io/ar-io/ao-su-binary:latest
            ghcr.io/ar-io/ao-su-binary:${{ github.sha }}

      - name: Build and push image to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          push: true
          context: servers/su
          file: RunDockerfile
          tags: |
            ghcr.io/ar-io/ao-su:latest
            ghcr.io/ar-io/ao-su:${{ github.sha }}
